### ISSUE TITLE
Practica1.proposisciones-logicas

### ISSUE THREAD

**Issue by Evelyn-sj13** [SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-Evelyn-sj13#1]
[Practica1.m.d.pdf](https://github.com/user-attachments/files/17528866/Practica1.m.d.pdf)

**Comment by mae18-25** [comment]
Portada:25/25
Procedimiento:25/25
Figuras, Ilustraciones y Fotografías:24/25
Resultados y conclusiones:24/25
Total:98/100

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
